version: '2'

services:
  test:
    image: busybox
    environment:
      Foo: $FOO
      Bar: $BAR
    command: "printenv"
  build:
    image: golang
    environment:
      Foo: $FOO
    command: "/bin/sh"