projects:  
  projectPath:
    inline:
      FOO: BAR
    openshift:
      - clusterURL:   https:/foo.bar
        namespace:    Foobar
        fieldselector:
          type: Opaque
        mapping:
          secret:
            USERNAME: username  # ENV : part-of-secert
            PASSWORD: password 

